services:
  db:
    image: postgres:15
    container_name: kornka_db
    restart: always
    environment:
      POSTGRES_USER: hyve
      POSTGRES_PASSWORD: pwd-senyo197
      POSTGRES_DB: kornka_db
    ports:
      - '5433:5433'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: trade_manager
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
